name: xiaolangze
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  tdesign_flutter: ^0.2.7
  fluttertoast: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/images/bg.png
    - assets/images/welcome.png

  fonts:
    - family: youSheBiaoTiYuan
      fonts:
        - asset: assets/font/优设标题圆.otf
